apiVersion: v1
kind: PersistentVolume
metadata:
  name: ikonewka-backend-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent_volumes/ikonewka_backend/storage"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ikonewka-backend-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
