apiVersion: v1
kind: PersistentVolume
metadata:
  name: ikonewka-mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent_volumes/ikonewka_mysql/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ikonewka-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
