apiVersion: v1
kind: Service
metadata:
  name: ikonewka-mysql-service
spec:
  selector:
    app: ikonewka-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002
  type: NodePort
