apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikonewka-mysql-deployment
spec:
  selector:
    matchLabels:
      app: ikonewka-mysql
  template:
    metadata:
      labels:
        app: ikonewka-mysql
    spec:
      containers:
        - name: ikonewka-mysql-container
          image: 192.168.0.2:5000/ikonewka_mysql_image:1.0.1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: ikonewka-mysql-pv-storage
      volumes:
        - name: ikonewka-mysql-pv-storage
          persistentVolumeClaim:
            claimName: ikonewka-mysql-pvc


